name: throttle-io-stream
version: '0.2.0.0'
synopsis: Throttler between arbitrary IO producer and consumer functions
description: To be written.
category: Concurrency
author: Moritz Schulte
maintainer: mtesseract@silverratio.net
copyright: (c) 2017 Moritz Schulte
license: BSD3
github: mtesseract/io-throttle
extra-source-files:
- README.md
ghc-options:
- -Wall
- -fno-warn-type-defaults
dependencies:
- base >=4.7 && <5
- stm
- async
- stm-chans
- clock
- text
library:
  source-dirs: src
  exposed-modules:
  - Control.Concurrent.Throttle
